import {
  columnFacetingFeature,
  columnFilteringFeature,
  columnSizingFeature,
  columnVisibilityFeature,
  createFacetedRowModel,
  createFacetedUniqueValues,
  createFilteredRowModel,
  createPaginatedRowModel,
  createSortedRowModel,
  createTableHookContexts,
  filterFn_arrHas,
  filterFn_arrIncludes,
  filterFn_arrIncludesAll,
  filterFn_arrIncludesSome,
  filterFn_between,
  filterFn_betweenInclusive,
  filterFn_empty,
  filterFn_endsWith,
  filterFn_equals,
  filterFn_equalsString,
  filterFn_equalsStringSensitive,
  filterFn_inDateRange,
  filterFn_inNumberRange,
  filterFn_includesString,
  filterFn_includesStringSensitive,
  filterFn_notEmpty,
  filterFn_startsWith,
  filterFn_weakEquals,
  globalFilteringFeature,
  metaHelper,
  rowPaginationFeature,
  rowSelectionFeature,
  rowSortingFeature,
  sortFn_alphanumeric,
  sortFn_basic,
  sortFn_datetime,
  sortFn_text,
  tableFeatures,
} from '@tanstack/react-table'

import type { TableColumnMeta, TableMeta } from './table.types'
import {
  dateFilterFn,
  numberFilterFn,
  selectFilterFn,
  stringFilterFn,
  viewModePlugin,
} from './table.utils'

const features = tableFeatures({
    columnFacetingFeature,
    columnFilteringFeature,
    columnMeta: metaHelper<TableColumnMeta>(),
    columnSizingFeature,
    columnVisibilityFeature,
    facetedRowModel: createFacetedRowModel(),
    facetedUniqueValues: createFacetedUniqueValues(),
    filterFns: {
      arrHas: filterFn_arrHas,
      arrIncludes: filterFn_arrIncludes,
      arrIncludesAll: filterFn_arrIncludesAll,
      arrIncludesSome: filterFn_arrIncludesSome,
      between: filterFn_between,
      betweenInclusive: filterFn_betweenInclusive,
      date: dateFilterFn,
      empty: filterFn_empty,
      endsWith: filterFn_endsWith,
      equals: filterFn_equals,
      equalsString: filterFn_equalsString,
      equalsStringSensitive: filterFn_equalsStringSensitive,
      inDateRange: filterFn_inDateRange,
      inNumberRange: filterFn_inNumberRange,
      includesString: filterFn_includesString,
      includesStringSensitive: filterFn_includesStringSensitive,
      notEmpty: filterFn_notEmpty,
      number: numberFilterFn,
      select: selectFilterFn,
      startsWith: filterFn_startsWith,
      string: stringFilterFn,
      weakEquals: filterFn_weakEquals,
    },
    filteredRowModel: createFilteredRowModel(),
    globalFilteringFeature,
    paginatedRowModel: createPaginatedRowModel(),
    rowPaginationFeature,
    rowSelectionFeature,
    rowSortingFeature,
    sortFns: {
      alphanumeric: sortFn_alphanumeric,
      basic: sortFn_basic,
      datetime: sortFn_datetime,
      text: sortFn_text,
    },
    sortedRowModel: createSortedRowModel(),
    tableMeta: metaHelper<TableMeta>(),
    viewModePlugin,
  }),
  { tableContext, cellContext, headerContext, useTableContext, useCellContext, useHeaderContext } =
    createTableHookContexts<typeof features>()

export {
  cellContext,
  features,
  headerContext,
  tableContext,
  useCellContext,
  useHeaderContext,
  useTableContext,
}
